### ISSUE TITLE
Launcher 2.0 to-do list

### ISSUE THREAD

**Issue by the-sane** [starcitizen-lug/lug-helper#87]
- [x] Update https://github.com/starcitizen-lug/lug-helper/pull/81 for the latest 2.0 launcher download
- [x] Set CLI mode on for new installs in the json (https://github.com/starcitizen-lug/lug-helper/pull/88)
- [x] Merge https://github.com/starcitizen-lug/lug-helper/pull/81
- [x] Re-arrange the Runners list in the Helper so GE is lower down in the list and Kronek is first (https://github.com/starcitizen-lug/lug-helper/commit/2e6b08fd271e4a4b3bea264d1a6a06e6d1dd2835)

**Comment by mactan-sc** [comment]
would suggest including STORE and PROTONPATH variables so that users can freely switch to proton and have star citizen protonfixes invoked

for lutris 5.17 compatibility these would also need to be in the "prefix_command" value 
https://github.com/starcitizen-lug/lug-helper/compare/main...mactan-sc:lug-helper:protonversion
